### ISSUE TITLE
Add sample certificates

### ISSUE THREAD

**Issue by rjchow** [OpenCerts/opencerts-documentation#10]
For people to play with and see what a cert looks like, and to see how failure to verify looks like

**Comment by wmclaxton** [comment]
The sample cert does not validate using the form on this page (https://opencerts.io/).  Is that intentional? 
As an alternative, could you provide a sample certificate that works?

**Comment by ryansena** [comment]
Agree please add sample certs, or possible way to view certs/transcripts without the hash/root.

**Comment by yehjxraymond** [comment]
Hi, thanks everyone for alerting us that the sample files were obsolete.

I've updated with a sample that you can use at dev.opencerts.io (connected to Ropsten test net)

Will proceed to close this issue.

**Comment by ryansena** [comment]
Tried loading the sample (NP_SAMPLE_PHARM.opencert) to dev.opencerts.io
I got this error:
"File cannot be read. Please check that you have a valid .opencert file"

**Comment by yehjxraymond** [comment]
Can you check that it is not in a zipped file or folder?

**Comment by wmclaxton** [comment]
Using either drag and drop or file system browser, I receive the error "This certificate is not valid. The certificate records are not found. The certificate has been revoked."  Attached is the file I am testing with, copied from your sample.  As you can see, it is not zipped - it's plain text/XML.

[NP_SAMPLE_PHARM.opencert.txt](https://github.com/OpenCerts/opencerts-documentation/files/2769813/NP_SAMPLE_PHARM.opencert.txt)

**Comment by yehjxraymond** [comment]
wmclaxton, that’s an error you see if you are on the main site, please use dev.opencerts.io

**Comment by wmclaxton** [comment]
Ok, tested the NP_SAMPLE_PHARM.opencert certificate file is working on the validator at https://dev.opencerts.io/.  Thanks!

**Comment by yehjxraymond** [comment]
Yw, please create another issue if there are other problems. This issue is now closed.
