### ISSUE TITLE
Issue in printing opencert file

### ISSUE THREAD

**Issue by osvvinodp** [OpenCerts/opencerts-documentation#101]
Hi,

We have issue while saving opencert file as PDF using print button on opencerts.io site.
Print preview is not showing opencert file content.
Please find attached screenshot.
Please let us know how this can be fixed? 

Let us know if you need more information.

![Print Preview](https://user-images.githubusercontent.com/61730690/75756271-59575180-5d6b-11ea-9c9f-42a65734ce81.JPG)

**Comment by Nebulis** [comment]
Did you try to click on the print button in the website?

**Comment by osvvinodp** [comment]
Yes, We tried print button in website. it gives same preview as previous screenshot.

Yes, we used custom renderer.

**Comment by Nebulis** [comment]
do you have a link tto your code ?

the renderer should receive an action (PRINT) from the frame. from the action only call window.print

if you used one of our template, you can eventually update the libs

adr => https://github.com/Open-Attestation/adr/blob/master/decentralised_rendering.md

**Comment by osvvinodp** [comment]
Please find attached template file
[transcript.zip](https://github.com/OpenCerts/opencerts-documentation/files/4284557/transcript.zip)

**Comment by Nebulis** [comment]
I explained you the reason above. 

If your code is accessible I can try to help you otherwise just the certificate won't help

**Comment by Nebulis** [comment]
If you inialized your project with https://github.com/Open-Attestation/decentralized-renderer-react-template or with your project uses a dependency called `decentralized-renderer-react-components`, upgrade this dependency to the latest version

**Comment by osvvinodp** [comment]
Please find below link. Please help to verify any changes need to be done?
We noticed some upgrades in package.json in latest version.

https://github.com/nikhilranosys/demo-opencerts-renderer/tree/smu-templates-new

**Comment by Nebulis** [comment]
upgrade govtechsg/decentralized-renderer-react-components to the latest version

**Comment by osvvinodp** [comment]
Hi,

Apologies, We are still not into decentralized-renderer-react-components. 

Please find our active code url.

https://github.com/nikhilranosys/demo-opencerts-renderer/tree/smu-templates

Please verify and let us know issue for print.

**Comment by Nebulis** [comment]
https://github.com/nikhilranosys/demo-opencerts-renderer/blob/smu-templates/src/components/documentViewer/documentViewerContainer.js#L88

Here you need to create a function named `print` that calls `window.print()`

**Comment by osvvinodp** [comment]
Hi,

We tried locally adding print function in documentViewerContainer.js but still we are facing print error.

Could you please check again if there is any other issue? Also could you please explain why our template is facing this print error? is there anything we need to change in our template?

**Comment by Nebulis** [comment]
I dunno what you did but I tried locally and it works

![image](https://user-images.githubusercontent.com/503185/76379419-fb3df600-638a-11ea-9626-f197ebe693b5.png)

I suggest you to just start from the template we provide and directly paste your components

**Comment by osvvinodp** [comment]
Hi,

This issue is resolved after we place code in actual Renderer. But some how locally i faced issue.
This issue can be closed now.

Thanks for your support.
