### ISSUE TITLE
version comparison

### ISSUE THREAD

**Issue by wmclaxton** [OpenCerts/opencerts-documentation#106]
Where can I find a document which lists the changes between 1.5 and 2.0?

**Comment by Nebulis** [comment]
Damn, I realised I didnt port back this fro the previous doc. You can find the info => https://github.com/OpenCerts/opencerts-documentation/blob/master/legacy/announcements/schema2_update.md

**Comment by wmclaxton** [comment]
Thank you for the quick response.

**Comment by Nebulis** [comment]
it's back => https://docs.opencerts.io/docs/migrations/v1_to_v2
