### ISSUE TITLE
UAT deployment for the custom templates

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#11]
Hi,

For deploying custom template to UAT, is it following the same steps as per replied by your team in the hyperlink below?
https://github.com/OpenCerts/opencerts-documentation/issues/6

Please advise.
Thanks.

**Comment by rjchow** [comment]
There's no separate deployment for UAT and Prod, all successfully completed PRs are deployed immediately to UAT and Prod at the same time.

(UAT is strictly for testing transactions on Ropsten testnet only and not UI testing)

You can use the PR preview function to view your changes before it is deployed.

![image](https://user-images.githubusercontent.com/27843274/48327530-35559580-e67a-11e8-8db5-682b7dc4e9c9.png)
