### ISSUE TITLE
Use revocation functionality in Node.js based application

### ISSUE THREAD

**Issue by eujinong123** [OpenCerts/opencerts-documentation#110]
I wanna implement the feature to revoke certificates in my node.js application. But I didn't find any proper method in open certificate node packages.
Revoking open certificates is restricted to your admin console?

**Comment by Nebulis** [comment]
Hi,

this package will help you => https://github.com/Open-Attestation/document-store
it's also doable using open-attestation-cli => https://github.com/Open-Attestation/open-attestation-cli#revoke

**Comment by eujinong123** [comment]
Thank you for your help, @Nebulis

**Comment by eujinong123** [comment]
Hi, @Nebulis 

We only issue Merkle tree root hash on Ethereum Blockchain after signing batched OpenCerts. And then if there became need to revoke one particular certificate, we revoke target hash of it on Blockchain.

In this case, the batch's Merkle tree root hash should be recalculated again?
Please correct me, if I am wrong.

Thank you.

**Comment by rjchow** [comment]
no need, the rest of the tree is still valid - just that particular target hash of that one cert is revoked

**Comment by eujinong123** [comment]
Thank you for your kind explanation.
