### ISSUE TITLE
Using OpenCerts.io for organization in other countries

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/opencerts-documentation#112]
I did OpenCerts implementation for one of our client in singapore and now we are planing to develop a product on it which can be deployed for any university or other organization for issuing certificate on block chain and those certificates can be verified on OpenCerts.io. So I have below queries for this matter:

1. Can universities from other countroes use OpenCerts.io for verification of certificates (if they use DNS-TXT record for verification)?
2. Can organizations other then educational institutions also use OpenCerts.io?

**Comment by yehjxraymond** [comment]
1. Yes
2. Yes

We don't discriminate😁

I've a suggestion that for (2), they should check out the OpenAttestation standards instead, it has a more liberal schema, so that you won't have to conform to the fields required. It will still render fine on the site.

**Comment by yehjxraymond** [comment]
http://openattestation.com/
