### ISSUE TITLE
Error in deployment of Opencerts 2.0 renderer to netlify 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/opencerts-documentation#114]
I followed the steps stated in documentation : https://openattestation.com/docs/verifiable-document/document-template  but hitting some error during the build 
--------
Failing build: Failed to build site
Failed during stage 'building site': Deploy directory 'dist' does not exist
-------

Any advice to resolve this. 

Error log 
9:56:10 AM: ┌─────────────────────────────┐
9:56:10 AM: │   Netlify Build Complete    │
9:56:10 AM: └─────────────────────────────┘
9:56:10 AM: ​
9:56:10 AM: (Netlify Build completed in 1m 5.1s)
9:56:10 AM: Caching artifacts
9:56:10 AM: Started saving node modules
9:56:10 AM: Finished saving node modules
9:56:10 AM: Started saving build plugins
9:56:10 AM: Finished saving build plugins
9:56:10 AM: Started saving yarn cache
9:56:10 AM: Finished saving yarn cache
9:56:10 AM: Started saving pip cache
9:56:10 AM: Finished saving pip cache
9:56:10 AM: Started saving emacs cask dependencies
9:56:10 AM: Finished saving emacs cask dependencies
9:56:10 AM: Started saving maven dependencies
9:56:10 AM: Finished saving maven dependencies
9:56:10 AM: Started saving boot dependencies
9:56:10 AM: Finished saving boot dependencies
9:56:10 AM: Started saving go dependencies
9:56:10 AM: Finished saving go dependencies
9:56:12 AM: Build script success
9:56:12 AM: Failing build: Failed to build site
9:56:13 AM: Failed during stage 'building site': Deploy directory 'dist' does not exist
9:56:13 AM: Finished processing build request in 1m58.079043367s

![image](https://user-images.githubusercontent.com/47696120/86424836-2cfe1280-bd16-11ea-9394-a61db1afcfb0.png)

**Comment by Nebulis** [comment]
Dist should be the folder where your bundle has been outputted

If you used the template as in the doc it should work otherwise if you used a different way to build your template then it might be different

How did you create the template? Any code to link to?

**Comment by RP-OIS-SK** [comment]
Thanks for your reply. 

The code is from based on https://github.com/SP-INDT-OpenCert/demo-opencerts-renderer which is forked from https://github.com/OpenCerts/demo-opencerts-renderer

I have reused some of the code from https://github.com/OpenCerts/legacy-templates as well. 

Separately,  I have forked from https://github.com/OpenCerts/demo-opencerts-renderer and deployed to netlify.  I got the same error as well.  Is there any deployment setting need to modify ?

**Comment by Nebulis** [comment]
You probably forked before we changed https://github.com/OpenCerts/demo-opencerts-renderer to use https://github.com/Open-Attestation/decentralized-renderer-react-template.

The benefit of https://github.com/Open-Attestation/decentralized-renderer-react-template is that it abstracts away the frame connection (for instance no more this https://github.com/SP-INDT-OpenCert/demo-opencerts-renderer/tree/master/src/components/documentViewer)


> Separately, I have forked from OpenCerts/demo-opencerts-renderer and deployed to netlify. I got the same error as well. Is there any deployment setting need to modify ?
I'm not sure what you tried, but this is the deployment config for https://github.com/OpenCerts/demo-opencerts-renderer
![image](https://user-images.githubusercontent.com/503185/86432332-edd9bc80-bd29-11ea-8e48-e022e2cc7c63.png)

> Back to your problem
You use create-react-app and if I'm not wrong the output dir is build not dist, try to change publish directory to build

**Comment by RP-OIS-SK** [comment]
I was following the instruction on https://openattestation.com/docs/verifiable-document/document-template  which is 
------
Select "New Site From Git" and then "GitHub".
On the build page, enter npm run build as the "Build command" and dist as the "Publish Directory" and click on "Deploy Site". 
---
Any new instruction ? where do I select "create-react-app" ? 

The default is  

"yarn build" for the build command 
and "build/" published directory

**Comment by Nebulis** [comment]
https://openattestation.com/docs/verifiable-document/document-template is showing an example using https://github.com/Open-Attestation/decentralized-renderer-react-template

You are using an older version of a template which is using `create-react-app` under the hood (as you can from your repository https://github.com/SP-INDT-OpenCert/demo-opencerts-renderer/blob/master/package.json#L24). `create-react-app` is a tool that helps you to build react application, you don't have to select it.

So in your case, because your template is using `create-react-app` you have to change a bit netlify deployment.

The only change that should be required if I'm correct is
- publish directory: build

**Comment by RP-OIS-SK** [comment]
I do not see "publish directory"  in package.json, where should I put it ?  
---------------
{
  "name": "oa-doc",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.22",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@govtechsg/open-attestation": "^1.1.39",
    "bootstrap": "^4.3.1",
    "date-fns": "^1.30.1",
    "lodash": "^4.17.15",
    "moment-timezone": "^0.5.26",
    "node-sass": "^4.14.1",
    "number-to-words": "^1.2.4",
    "penpal": "4.1.1",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-pdf": "^4.1.0",
    "react-scripts": "^3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "CI= react-scripts build",
    "test": "react-scripts test --testPathPattern=\\.test.js$",
    "serve-static": "http-server build -s -p 3000",
    "test-coverage": "npm run test -- --coverage --watchAll=false",
    "integration": "testcafe chrome src/**/*.spec.js",
    "integration:headless": "testcafe chrome:headless src/**/*.spec.js",
    "eject": "react-scripts eject",
    "lint": "eslint . --ext .js --max-warnings 0",
    "lint:fix": "eslint . --ext .js --fix"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "babel-plugin-dynamic-import-webpack": "^1.1.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "eslint-config-prettier": "^6.1.0",
    "eslint-plugin-jest": "^22.15.2",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "http-server": "^0.12.3",
    "prettier": "^1.18.2",
    "react-test-renderer": "^16.9.0",
    "sinon": "^7.4.1",
    "testcafe": "^1.4.1"
  }
}

**Comment by Nebulis** [comment]
In netlify configuration

**Comment by RP-OIS-SK** [comment]
thanks...it is working now
