### ISSUE TITLE
OpenCerts issuance validation

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#118]
We had an accidental issuance of OpenCerts on the Metamask site but with the Ledger Nano cryptowallet, and the transaction went through spending the actual Ether. The issuance had to be done again in the Ledger site to make the certs valid.
Would it be possible to have validation to prevent this issue?

**Comment by Nebulis** [comment]
Hi, I guess you are referring to admin.opencerts.io for the issuance (Metamask site and Ledger site)

What kind of validation do you expect us to setup regarding your issue ? Metamask wallet is valid, Legdger is valid, we have no way to know you are using the correct account to issue a document.

**Comment by yvonneyong** [comment]
Would it be possible to ensure actual Ether is not spent on Metamask site?

**Comment by Nebulis** [comment]
AFAIK it's not possible:
- some might use metamask on production
- we are considering providing ledger support through metamask because the current website doesn't work on firefox browsers
