### ISSUE TITLE
openatts: command not found

### ISSUE THREAD

**Issue by Dimple-Kanwar** [OpenCerts/opencerts-documentation#120]
Hi,
I was trying out the following command:
openatts net=ethereum netId=3 addr=$DOCUMENT-STORE-ADDRESS

OUTPUT:
openatts: command not found
I could not find anywhere about its installation guide.
Can you please help me in installing this?

Thanks in advance.

**Comment by rjchow** [comment]
it’s not a command it’s a dns-txt record

**Comment by Dimple-Kanwar** [comment]
is there any pre-requisite before running this command? because i am getting this error message. How can i resolve this issue?

**Comment by Nebulis** [comment]
As explained above and in [the documentation](https://openattestation.com/docs/advanced/configuring-dns#inserting-the-dns-record) this is not a command to run and you need to do follow instruction and head to your domain registrar
