### ISSUE TITLE
Adding new font files to the project

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#14]
Hi,

Do you have any samples that loaded and added new font file (ttf file) to the project?
Thank you.

**Comment by yehjxraymond** [comment]
Hey Erwin,

We do not recommend the use of custom fonts as it will increase the load time for ALL users on the site.

**Comment by erwinsg** [comment]
Hi Raymond,

Thanks for quick reply. This is as per request from SIT so that the certificate looks similar to hard copy of the certificate.

**Comment by rjchow** [comment]
I will investigate to see if there's a way to do it without impacting the experience of all users, but don't be too hopeful about it. In the mean time let your stakeholders know that this is unlikely to be possible and that they should consider relaxing their constraints on font choices.

**Comment by erwinsg** [comment]
Hi Raymond,

ok noted with thanks.
