### ISSUE TITLE
Custom Template - Deploying Store for production use

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#17]
Hi,

I will be conducting UAT with SIT (Singapore Institute of Technology) sometime this week. What i wanted to check is, for production, will SIT be creating the store using this website https://admin.opencerts.io/ and using free token (Metamask)?

Please advise, as I will need to update the custom template with the store address.

**Comment by rjchow** [comment]
Depends on the goal of your UAT, if it is to test the template rendering
then it is ok.


If it is to educate the full workflow then I would suggest using a Ledger
Nano S on the Ropsten testnet to make sure the "user" understands how to
use one.

**Comment by erwinsg** [comment]
Dear Rui Jie,

Thanks for your prompt reply.
If user deploy the store using free token (Metamask), does it mean that they need to re-deploy the store again for production by using Ledger Nano S hardware security module?

**Comment by rjchow** [comment]
yes

**Comment by erwinsg** [comment]
If it is double work for the user, I would like to ask them to deploy the store using Ledger Nano S hardware security module instead. 

As from what I read from the hyperlink that you gave us, user can send testnet ethers to their wallet for their UAT too, and it will not be charging from their main wallet.

Is my understanding correct?

**Comment by rjchow** [comment]
Either way they'll have to deploy once for testnet and once for mainnet,
same even with Ledger Nano. In any case they should not be afraid of doing
it.



Your understanding is correct, testnet ether and mainnet ether are
completely separate and therefore the deployments are separate as well.

**Comment by erwinsg** [comment]
Hi Rui Jie,

After they issue the certificate, how did opencerts website differentiate cert issuance between UAT (issued using testnet ethers) and production (issued using mainnet ethers)?

Is this website https://dev.opencerts.io/ only for UAT? For production, is there other opencerts website URL?
