### ISSUE TITLE
Committed code to my branch for custom template

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#18]
Hi,

I have just committed the custom template for Singapore Institute of Technology to my branch (https://github.com/erwinsg/opencerts-website.git).

Please refer to below for my commit info:

1. First commit
Commit: 1d704bd93dc3a1f5135e891bbdadc3aeb4898368 [1d704bd]
Parents: d20c950939
Author: NCS\P1201675 <erwin.sg@ncs.com.sg>
Date: Monday, December 3, 2018 9:30:53 PM
Committer: NCS\P1201675
Description: NCS: eCert Template for SIT

2. Second commit
Commit: 5d9b0e570410882b62e6ca64bbdfea7a5852002a [5d9b0e5]
Parents: 1d704bd93d
Author: NCS\P1201675 <erwin.sg@ncs.com.sg>
Date: Wednesday, December 5, 2018 3:02:59 PM
Committer: NCS\P1201675
Description: NCS: eCert Template for SIT_20181205

Please let us know once it is deployed to opencert website https://dev.opencerts.io/, so that we can inform Singapore Institute of Technology to start their UAT.

**Comment by yehjxraymond** [comment]
An example of a PR: https://github.com/OpenCerts/opencerts-website/pull/39/checks?check_run_id=32436771

You can see that the site will automatically be deployed and you can preview it from there.

**Comment by erwinsg** [comment]
Thanks Raymond,

Please refer to below for your checking.
https://github.com/OpenCerts/opencerts-website/pull/55

**Comment by erwinsg** [comment]
There seems to be some error as per below hyperlink
https://travis-ci.org/OpenCerts/opencerts-website/builds/463718080?utm_source=github_status&utm_medium=notification

can please advise?

**Comment by erwinsg** [comment]
There are conflict on this file below, which I have resolved in my branch.
# Conflicts:
#	src/components/CertificateTemplates/index.js
