### ISSUE TITLE
Error after merging the latest file

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#19]
Hi,

I faced this issue as per attached file after i merged the latest file. Please assist.
Thank you.

[err_logs.txt](https://github.com/OpenCerts/opencerts-documentation/files/2648772/err_logs.txt)

**Comment by erwinsg** [comment]
Hi,

I am trying to pull the latest changes from master, but seems to have error due to previous config. Please assist.

![err_20181205](https://user-images.githubusercontent.com/43283667/49518043-9e76a480-f8d8-11e8-9da9-061605c862da.png)

**Comment by rjchow** [comment]
you'll have to resolve the merge conflict, my preferred method is to do a rebase of your branch on to the latest master

**Comment by erwinsg** [comment]
hi Rui Jie,

I have troubled merging my files as I am not familiar with github. Can please advise?
Thank you.

![image](https://user-images.githubusercontent.com/43283667/49578104-e9012b00-f983-11e8-8bc4-34ccf46a7e97.png)
