### ISSUE TITLE
Open CERTS General Questions

### ISSUE THREAD

**Issue by solaikani** [OpenCerts/opencerts-documentation#21]
•	Where can we purchase the Ledger Nano S Hardware Wallet Device?
•	How to purchase ethereum?
•	What software do we need to prepare and which system should it be installed in?
•	Can we do some testing once we set up the system? Like issue a dummy cert to a dummy participant and see if can be received etc?
•	How do we monitor/verify that the e-Certs are correctly uploaded?

**Comment by rjchow** [comment]
1,2. Anywhere that is convenient for you, we do not have a designated supplier
3. https://github.com/OpenCerts/opencerts-documentation/blob/master/batching_certificates.md#cli-tool
4. https://github.com/OpenCerts/opencerts-documentation/blob/master/appendix_test_accounts.md , https://github.com/OpenCerts/opencerts-documentation/blob/master/issuing_certificates.md
5. https://opencerts.io for main net (production) certs and https://dev.opencerts.io for testnet certs

**Comment by yehjxraymond** [comment]
Will close this issue since there is no further question
