### ISSUE TITLE
Fork Clone issue

### ISSUE THREAD

**Issue by alagu1983** [OpenCerts/opencerts-documentation#22]
Hi Team,

This is for SP project.
We are setting up Fork project in order to correct&push the template from local machine to server.
 #Issue 1: We getting  error "remote: Permission to mmysgp/opencerts-website.git denied `Username`. Fatal : Unable to access "https://github.com/mmysgp/opencerts-website.git": the requested URL returned error 403.
Above error occurred at the step 3(second command) of the below sequence.
1. Clone the forked copy to local PC:
> C:\GovTech\new_v1.5\NP_Fork_Copy>git clone https://github.com/mmysgp/opencerts-website.git
> cd opencerts-website
2. setup remote (original project url)
> git remote add upstream https://github.com/OpenCerts/opencerts-website.git
3. create branch
> git checkout master
> git pull upstream master && git push origin master.

Please help us in resolving the same.

We have couple of doubt since a beginner.
Question 1: As per the fork project setup to push the template to server. Weather the template will be pushed to real Open cert web site server or to the Github server ? Which command of below logically connects to the server by push.

Below is the planned setup command we are planning:
Fork Github Project

1. Fork the project

2. Clone the forked copy to local PC:
> C:\GovTech\new_v1.5\NP_Fork_Copy>git clone https://github.com/mmysgp/opencerts-website.git
> cd opencerts-website

3. setup remote (original project url)
> git remote add upstream https://github.com/OpenCerts/opencerts-website.git

4. create branch
> git checkout master
> git pull upstream master && git push origin master
> git checkout -b npviewer/dpp-cert

5. configure local system for checking in account.
> git config --global user.email "developer's email address"
> git config --global user.name "developer's name"

6. modify your code in the local copy of opencerts_website

7. fix code style issue
> yarn lint --fix

8. commit the changes
> git add . 
> git commit -m "fix alignment issue for date in option certificate." 

9. create PR (update branch in Github)
first time:
> git push -u origin npviewer/dpp-cert
subsequent:
> git push origin

Thanks in advance.

**Comment by rjchow** [comment]
I can see a couple of issues here, the one that's causing your immediate issue of the 403 is that the mmysgp/opencerts-website fork is owned by Yong Wu - that is why you do not have permissions to push to his fork.

I think you will find it very helpful to understand how Git and GitHub works before attempting this, try https://guides.github.com/activities/hello-world/ and https://www.dataschool.io/simple-guide-to-forks-in-github-and-git/

**Comment by alagu1983** [comment]
Hi rjchow, 

Thanks for the reply.

**Comment by alagu1983** [comment]
Hi, I have understand the forking the project. Here what i can understand is once you forking is done. Push & Pull will sync object from local system to Github server of the owners repository.
 We are actually planning to use Github for open certs. Can we know how Opencerts will recognize the updated object once the object is synchronized with Github?
 For example: When a template is developed for certificate in local machine and pushed to git hub server using push. How this updated template will be identifies/sync to Open cert site while viewing the certificate?. Thanks.

**Comment by rjchow** [comment]
When you have pushed to your fork and are ready for testing on OpenCerts, you may make a pull request to us against your repository, that will allow us to vet your changes and subsequently merge it.

You can find more information [here](https://github.com/OpenCerts/opencerts-documentation/blob/master/custom_template.md) , and [here](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)

**Comment by alagu1983** [comment]
Thanks for the reply
