### ISSUE TITLE
Unable to open certificate in viewer - Certificate from unregistered institution

### ISSUE THREAD

**Issue by alagu1983** [OpenCerts/opencerts-documentation#24]
Hi Team,

i have hosted the Opencert clone website in my machine and perform a node command in Certificate-cli master in order to move the unsigned certificate to Singed certificate folder.

When i trying to view the signed certificate(Json file) in the local cloned website"http://localhost:3000/", i am getting the below error.
When i trying in the "https://dev.opencerts.io/" i am getting the same error as below.
Error message: 
/********************************************************************************************/
This certificate is not valid
The certificate records are not found
Certificate from unregistered institution
We are unable to verify the certificate as this institution has not registered with OpenCerts
/********************************************************************************************/
I am beginner in this subject Please guide what i am missing here and what should i need to do?.

Thanks

**Comment by yehjxraymond** [comment]
Hi, can you please post your certificate here?

**Comment by alagu1983** [comment]
Below is the signed certificate

{
  "schema": "opencerts/v1.4",
  "data": {
    "id": "93509bc5-c1e7-418b-9a43-15b1cd7930cc:string:SP-4",
    "name": "2ef63aaf-99ca-4559-a717-2bc0e92b38ca:string:Diploma in Computer Engineering",
    "issuedOn": "8740eda9-fc5d-4e13-ba20-b2df727b84a6:string:2018-08-01T00:00:00+08:00",
    "issuers": [
      {
        "name": "35064096-7b95-4388-a8a1-a1a8ab52b7ad:string:PACE Academy",
        "certificateStore": "98393985-5176-4a2b-ae41-6dfebee3f927:string:0x3B7b2E03bC37a017Fc67C668F8a5b9D3fd65c52e"
      }
    ],
    "recipient": {
      "name": "d2e1fd9a-0600-486f-8c8c-f9d258ded149:string:Miss Divyadharsni"
    },
    "transcript": [
      {
        "name": "cee71e61-2d22-4ca1-a9f0-4602b2dbe411:string:ET1600",
        "title": "3643d0aa-d043-42a4-b3c3-918b310969fb:string:Test Title",
        "grade": "15681f81-a164-45b8-b585-fbb2203426fd:string:C+",
        "unit": "593830e1-ef24-4551-94d0-3aa3feab92ec:string:5",
        "gpa": "5604dc5e-8818-46c0-9547-2b7154d77967:string:1.0"
      }
    ]
  },
  "privacy": {},
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "bc0aa9198c2024a575d9730d8962f2413a68c7d71d34069a38fddfb7f5610726",
    "proof": [
      "5a1c88ce22e87f1e816d9d8fe4b0b9738d81167fc7f8fea32900f2e928d3048f"
    ],
    "merkleRoot": "682ab594648dd1d3b50a9417ba5e75bf4256b3f98ecb80c03edb542958b639f5"
  }
}

**Comment by yehjxraymond** [comment]
**This certificate is not valid**
Can you check that you've not tampered with the certificate AFTER it is processed from the CLI? This result in the target hash failing

**The certificate records are not found**
This certificate with hash `682ab594648dd1d3b50a9417ba5e75bf4256b3f98ecb80c03edb542958b639f5` has not been issued. We notice that you've issued another certificate batch `f677117b150dfeb178ad5ff03b803a3734cb3487000000000000000000000000`, naturally it won't match. 

**Certificate from unregistered institution**
This is a warning, you will continue to see this message until we have whitelisted your address. You may safely ignore this

**Comment by yehjxraymond** [comment]
@rjchow pointed that the hash corresponded to your issuing address, please don't use that. In this case you should  be using `682ab594648dd1d3b50a9417ba5e75bf4256b3f98ecb80c03edb542958b639f5`, provided the certificate file has not been altered.

**Comment by alagu1983** [comment]
Hi ,
Thanks for your reply.
1. we have not altered the singed certificate file.
2. We are actually testing locally. we got a certificate key store from client. i performed issuing certificate using the URL "https://admin.opencerts.io" by selecting metamask. Still the issue presist.

Might be i am missing something on certificate issuing. What is significance of value in the drop down?. Whether it related to purchase of the certificate store?. Please guide in this regards thanks.

**Comment by rjchow** [comment]
Re: 2) I don't see your amended certificate issuance, only the faulty one from 5 days ago - make a new issuance with the hash value 0x682ab594648dd1d3b50a9417ba5e75bf4256b3f98ecb80c03edb542958b639f5

For your question on the dropdown box: https://github.com/OpenCerts/opencerts-documentation/blob/master/deploying_store.md#networkapplication-selection

**Comment by alagu1983** [comment]
Hi ,

Thanks, one last questions.

1. Even for viewing the certificate in local host & Dev open certs,  "https://admin.opencerts.io" url has to be used for segueing the certificate? or any other test issue URL is available respectively.
2. After issuing the certificate, the transaction has to be confirmed in respective network, May i rite?

Thanks.

**Comment by rjchow** [comment]
1) yes use https://admin.opencerts.io
2) after clicking the issue button on the website UI, you still have to actually send the transaction from your Ethereum wallet interface, either Metamask chrome extension or the Ledger Nano hardware wallet

**Comment by alagu1983** [comment]
Great, thank you very much

**Comment by sanchitdawarsd** [comment]
can i change .opencert extension?

**Comment by sanchitdawarsd** [comment]
to any other extension

**Comment by rjchow** [comment]
for best user experience we recommend you do not change the extension
