### ISSUE TITLE
Unable to View certificate

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/opencerts-documentation#25]
Hi, I had done the issuing of certificate after the CLI tool and got this error:

_The certificate records are not found
The certificate has been revoked
Certificate from unregistered institution
We are unable to verify the certificate as this institution has not registered with OpenCerts_

Here's a copy of my cert file for reference:
{
  "schema": "opencerts/v1.4",
  "data": {
    "id": "81a1c396-fd7e-4319-9aec-65a6fd211d7d:string:2018091259",
    "$template": "bb239e3b-e4bc-4c20-967d-571974bc5064:string:sg/edu/sp/SP-2019-MAIN",
    "name": "f1ec8770-4c5f-4a4a-8060-8713f60305ac:string:Diploma in Accounting",
    "issuedOn": "10b44a1b-b2ac-4638-aba5-f67d174e847c:string:2018-08-01T00:00:00+08:00",
    "issuers": [
      {
        "name": "54715d11-10fa-4a84-941e-04bd492de68f:string:Singapore Polytechnic",
        "certificateStore": "9a5f7870-3afc-4809-a2ae-03721644e5cd:string:0xDd545d84Dc8C0D2E024D3367be46108F81F62387"
      }
    ],
    "recipient": {
      "name": "58e3d7d1-20db-409e-80a3-698f4de91cc7:string:John Snow"
    }
  },
  "privacy": {},
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "44624818d100b506331290da1309c366da8bbfc45ecbd6cd653164cfc44a07a2",
    "proof": [],
    "merkleRoot": "44624818d100b506331290da1309c366da8bbfc45ecbd6cd653164cfc44a07a2"
  }
}

**Comment by ryansena** [comment]
Sorry, u can close this issue. I put a wrong store address.

**Comment by rjchow** [comment]
thanks
