### ISSUE TITLE
Tech Requirement for CLI Tool

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/opencerts-documentation#29]
Hi, 

I'm planning to deploy the CLI Tool to a new windows server, so we can automate the process from calling out CLI from our current system. Do we have any technical specs/requirements for the windows server?

**Comment by rjchow** [comment]
The dev team has no familiarity with the performance requirements on windows platforms, perhaps @mmysgp from Ngee Ann Polytechnic can chime in here?

**Comment by mmysgp** [comment]
It took 45 minutes to sign 7000+ certificates with the following configuration (on VM):
CPU: Intel(R) Xeon(R) E5-2695@2.1 GHz X 4
Memory: 32 GB

You may want to deploy a server with better specs in order to run faster.

**Comment by yehjxraymond** [comment]
Please see our latest announcements on the more efficient alg for the CLI. 

The new alg trades IO requirements for much lower memory requirements and is much more efficient in generating the proofs.

Closed due to inactivity
