### ISSUE TITLE
Unable to view certificate

### ISSUE THREAD

**Issue by chongsoon** [OpenCerts/opencerts-documentation#30]
Hi,

I issued the certificates, but the opencert mentioned that the cert is not found.

The following is the store address and the merkle root:

Store: 0x3FFB6b913E9874c7ddabD564d85676Bc5cAd16d4
Merkle: 0x40d96d7cccc80bee35bd33ba0b1862c9372d8da51f1543aec9decba2b42b3fa0

Please advise. Thank you.

**Comment by yehjxraymond** [comment]
Your certificate store is: 0x3FFB6b913E9874c7ddabD564d85676Bc5cAd16d4

The address you use is your own account address, not the certificate store.

You need to update your cert to use the right store, regenerate the new merkle root and re-issue

Note: Issued on ropsten

**Comment by chongsoon** [comment]
I am using the store address within the cert file. 

Referring to the latest transaction: 0x141ad2e4056d4c5280352004d16ed86384f773273fca96b597363f1145febf2b.

**Comment by yehjxraymond** [comment]
Could you attached your certificate here? If you have trouble uploading, can rename it with a .txt extension.

**Comment by chongsoon** [comment]
[ntu_cert_1.txt](https://github.com/OpenCerts/opencerts-documentation/files/2820374/ntu_cert_1.txt)
Attached is the file.

**Comment by yehjxraymond** [comment]
The attached file is the data of the certificate before it is passed into the CLI tool, could you attach the one that has the merkle root?

**Comment by chongsoon** [comment]
[ntu_cert_1.txt](https://github.com/OpenCerts/opencerts-documentation/files/2820445/ntu_cert_1.txt)
Attached is the signed file.

**Comment by yehjxraymond** [comment]
Found your problem, could you kindly update your CLI version by pulling the latest CLI and run a `npm install` or `yarn install` after that? The CLI tool you used has been depreciated and does not generate the right certificate. 

The cert file is missing some sort of type identifier if you are interested in what happened.

**Comment by chongsoon** [comment]
I see. Just tried and it works.
Thanks a lot.
