### ISSUE TITLE
Relationship between Certificate Store and issuance of certificates

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-documentation#32]
Will each issuance of certificates require a new deployment of Certificate Store on the ETH blockchain and will all certificates in the same batch share the same merkle root?

**Comment by yehjxraymond** [comment]
Only one store will be required. Subsequent issuance will be from the same store. 

Yes, all certificate in one batch will have the same root, but with different proofs.

**Comment by yehjxraymond** [comment]
Closed due to inactivity
