### ISSUE TITLE
Certificate Stores List I noticed reference to keeping a list of Certificate Stores.  Where is this maintained and what is the purpose of this list?

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-documentation#33]
I noticed reference to keeping a list of Certificate Stores.  Where is this maintained and what is the purpose of this list?

**Comment by yehjxraymond** [comment]
Please see: https://opencerts.io/static/registry.json.

This list is to tie the online identity to the physical identity of schools. Anyone can create their own certificate store and name it anything, so additional identity verification is required. 

However, one can skip the identity verification and the cert will still work, albeit with a identity warning on it.

This is akin to using a self-signed certificate on websites.

**Comment by yehjxraymond** [comment]
Closed due to inactivity
