### ISSUE TITLE
Persistent storage for certificate JSON files generated.

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-documentation#34]
Presumably the certificate JSON files are stored in some place which is accessible to the students, so that they can download and share them.  Where does OpenCerts store these files?

**Comment by yehjxraymond** [comment]
We do not store any files, the site simply checks that the certificate presented by the students are valid and render them.

**Comment by wmclaxton** [comment]
I refer to [this page](https://opencerts.io/).  It reads: "Whether you're a student or an employer, OpenCerts lets you verify the certificates you have of anyone from any institution."  The instructions read: "Drag and drop your opencert file to view its contents".  I am sure this refers to the JSON certificate data file.

So how does the student come into possession of this file?

**Comment by yehjxraymond** [comment]
@wmclaxton 
The individual institutes will need to figure that part out. The fastest way is to email them the certificate upon graduation, but a self-service portal will be ideal.

**Comment by yehjxraymond** [comment]
Closed due to inactivity
