### ISSUE TITLE
How is proof of authorship implemented for OpenCerts?

### ISSUE THREAD

**Issue by waichung** [OpenCerts/opencerts-documentation#35]
Am I correct that your verification process checks the digital signature of the issuer is valid and matches the signature of the issuer, or is this a planned feature?

**Comment by yehjxraymond** [comment]
The verification is 4 steps: 

Please see slide 6
https://docs.google.com/presentation/d/11QTk76_R_FRc5xrgLrkG-NjsIItYDNcLWG6RgiICm48/edit?usp=sharing

**Comment by wmclaxton** [comment]
Raymond,

So, am I correct that the process does not "check the digital signature of the issuer is valid and matches the signature of the issuer".  Is it also correct that there is no digital signature of the issuer in the cert and only the name of the issuer?  So the last check (#4 in your slides) is to review a (centralised) list of contract addresses that the issuer claims to control? 

Just as an aside, with all these proprietary certificate stores, white lists, contract address lists and revocation lists, it would be really helpful to have an illustration to clearly explain what is being checked.  In fact the verification process does not seem to be [documented here](https://github.com/OpenCerts/opencerts-documentation).

**Comment by yehjxraymond** [comment]
@wmclaxton 

Technically there is no signature of sort on the certificate, the document contains only:
- Hash of itself
- Merkle root of the entire batch of certificate (may or may not be issued at this point)
- Proof that the hash exist in the set of the batch
- Certificate store that it is (or will be) issued from

The issuance of the root on the certificate store then proofs that it has been issued by the owner of the store.

Finally, the centralised registry of identity ties that owner to an actual institute. We are still working on this section to explore how we can balance decentralisation and correctness of the identity records. 

Thanks for your suggestion, we will add the verification details to the documentation. Likely in the appendix section.

**Comment by wmclaxton** [comment]
Thanks Raymond.
