### ISSUE TITLE
Unable to deploy new instance

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/opencerts-documentation#39]
![image](https://user-images.githubusercontent.com/46921398/53609187-b83a3600-3c00-11e9-91bc-641917d7e071.png)
I tried to deploy new instance however the deployment seems to hang.

**Comment by rjchow** [comment]
![image](https://user-images.githubusercontent.com/27843274/53609769-5c24e100-3c03-11e9-8ad1-63a1fb61f901.png)

do you have this button?

**Comment by laykoonjune** [comment]
No, i do not have that button.

**Comment by rjchow** [comment]
please refer to https://docs.opencerts.io/appendix_test_accounts.html
