### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/opencerts-documentation#41]
Hi, 

I encounter the following error while trying to fix code style issue. Please advise how should i proceed. thanks. 
![image](https://user-images.githubusercontent.com/46921398/55143087-f9c6ee00-5178-11e9-9198-f719e17f8f55.png)

**Comment by rjchow** [comment]
add this above the offending line
// eslint-disable-next-line import/prefer-default-export

**Comment by laykoonjune** [comment]
Thanks. Manage to resolve it.
