### ISSUE TITLE
Inquiry on Custom Templates (Multiple Templates per Issuer)

### ISSUE THREAD

**Issue by thannehene** [OpenCerts/opencerts-documentation#43]
1. As per my understanding, a custom template can cater both the "Certificate" and "Transcript". It is mostly a segregated-view of a single JSON file (".opencert" file). In case of any subsequent view-interest within a single cert scope: e.g: The Detail section where the legend and ranking-standard are shown [static data], do we have any specific recommendations? 
   E.g: Should we display that as another tab in the View-Renderer [So, it will be "Cert..", "Transcript.." & "Details"]? 

2. Some cert-issuers may require to maintain multiple templates [not just the change of data]. 
a) Are there any limitations to this? 
b) What are the recommendations to handle this custom-template requirement?

3. What are the limitations & recommendations for the use of Water-marks in the templates?

**Comment by yehjxraymond** [comment]
1. Up to you. SEAB does that, look at their PR.
2. Look at NP PR
3. We don't recommend it because it doesn't add value, and it may impact user experience, there is no limitation though.

**Comment by rjchow** [comment]
1. No recommendation to date, we have left the institutions to manage this as they wish

2. None other than guidelines that have been listed in the documentation http://docs.opencerts.io/custom_template.html

3. No limitations or recommendations but you should feedback to your product owner that they add no additional security or in fact may be misleading, providing false security where there is none. The one place we have implemented a watermark as part of the OpenCerts framework is when it is printed - this is to tell the user that there are no security protections against modification when it is printed
