### ISSUE TITLE
Add writeup on frameless viewer

### ISSUE THREAD

**Issue by yehjxraymond** [OpenCerts/opencerts-documentation#44]

**Comment by rjchow** [comment]
its here http://docs.opencerts.io/embedded_viewer.html

**Comment by yehjxraymond** [comment]
Okay, will add the sample code in, I think the app is kinda broken cause of the link also..

**Comment by rjchow** [comment]
🤣 it's been the wrong url everywhere

**Comment by rjchow** [comment]
Also I was thinking of exposing some methods in the component for ease of use, right now its probably quite hard to integrate programmatically.

e.g methods for tab selection and input/update cert. basically have a think through what the developer experience is like to create use an embedded viewer

**Comment by yehjxraymond** [comment]
Great idea.
