### ISSUE TITLE
Unable to create new store address using ledger nano

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/opencerts-documentation#48]
Hi Raymond & Rui Jie, 

I am trying to create new store address for production using ledger nano, after accepting the transaction there are no store being deployed. Please advise.
Thanks in advance.

**Comment by laykoonjune** [comment]
0xD37Ce7259f0dc8F14B4BD588d00A72F508987Aca

**Comment by rjchow** [comment]
Any error inside the browser console? ctrl-shift-i for windows

**Comment by laykoonjune** [comment]
![image](https://user-images.githubusercontent.com/46921398/56479478-23f59c80-64e8-11e9-8197-19b521dc3686.png)

**Comment by rjchow** [comment]
Can you let me know the firmware version of your ledger nano? It's under the settings app, device > firmware

**Comment by laykoonjune** [comment]
1.1.8

**Comment by rjchow** [comment]
Try updating the firmware, https://support.ledger.com/hc/en-us/articles/360002731113-Update-device-firmware

**Comment by laykoonjune** [comment]
I have updated the firmware, there are still errors. 
![image](https://user-images.githubusercontent.com/46921398/56481104-ea289400-64ef-11e9-9dee-cab86b940402.png)

**Comment by rjchow** [comment]
let's check that we have a common understanding
steps in order:
1) open admin.opencerts.io
2) select ledger nano s from dropdown box
3) wait for correct address to show up on the top left, if address doesn't show up automatically then click on the circular arrow logo and wait until it does
4) type in issuer name
5) click deploy ... button changes to deploying...
6) confirm transaction on your ledger nano s
...
7) not deployed

is this correct?

Also can you check that the contract data setting inside the ethereum app on your ledger nano is set to "yes"?

**Comment by laykoonjune** [comment]
I just change the contract data setting inside the ethereum app to set to yes and able to deploy new store address. 
Thanks for your help.

**Comment by rjchow** [comment]
will see if we can make this more user friendly, thanks for letting us know about this
