### ISSUE TITLE
Is there a developer chat?

### ISSUE THREAD

**Issue by nickylimjj** [OpenCerts/opencerts-documentation#52]
Is there a developer chatroom going? It would be good for some real-time chat, especially for contributing.

**Comment by rjchow** [comment]
Not yet, would prefer to keep informative discussions on GitHub but I have just set up a Gitter for real time communications

[![Gitter](https://badges.gitter.im/OpenCerts/community.svg)](https://gitter.im/OpenCerts/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by nickylimjj** [comment]
Thanks?
