### ISSUE TITLE
Cross domain issue when calling Frameless viewer URL from Iframe.

### ISSUE THREAD

**Issue by Ananthan88** [OpenCerts/opencerts-documentation#53]
As the Frameless URL - https://dev.opencerts.io/frameless-viewer/
is on a different domain from our application we won't be able to interact with it when loaded in an iframe. 

Is there some other option such as postMessage available to interact with the URL when loaded in an iframe. We would likely need such mechanism to call the following methods - opencerts.renderCertificate, opencerts.templates, and opencerts.selectTemplateTab.

**Comment by rjchow** [comment]
Will have a think about how we can safely implement this.
May I ask what you're using the frameless viewer for?

**Comment by Ananthan88** [comment]
we are planning to use it display open-certs in our site.

**Comment by zhous** [comment]
Yeah, that's also my expectation. And we can then tightly collaborate together.

**Comment by ysong-suss** [comment]
Encountered the same issue as @Ananthan88

**Comment by rjchow** [comment]
Noted, we are looking into this

**Comment by rjchow** [comment]
We will not be providing a method for you to embed the opencerts.io website, instead you may self-host your own certificate rendering endpoints and use those instead. 

You may refer to https://docs.opencerts.io/announcements/schema2_update.html for details on this
