### ISSUE TITLE
Could not issue or revoke certificates

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#54]
We have been testing some batched certificates for the past week and it was working fine.
However, there seems to be an issue on the admin console today where issuing and revoking certificates is not working. It seemed only deploying certificate would trigger the wallet and gas price confirmation, but issuing and revoking did not.

**Comment by rjchow** [comment]
Could you do an animated recording of the process?

**Comment by yvonneyong** [comment]
I have it in an mp4 file but the file type is not supported here.

**Comment by rjchow** [comment]
hmm dropbox or google drive?

**Comment by yvonneyong** [comment]
https://youtu.be/JcVa6lmsY4o

https://youtu.be/tk6riLFJSsk

**Comment by rjchow** [comment]
prefix the values with 0x , sorry for the terrible user feedback, we're
actively working to improve it

**Comment by yvonneyong** [comment]
ooh.. strange, I don't recall doing that in previous issuance.
Thanks!

**Comment by rjchow** [comment]
no prob hope that solves it for you!

**Comment by yvonneyong** [comment]
Yes, thanks it was solved.
We got a little mixed up on the hash to use for revoking the cert.
We revoked the "proof" of one of the certs, and it revoked another cert from the same batch, and realized it was because it was the "target hash" of that cert.
It would be good to get some clarity on the proof data in the cert.

**Comment by calebytes** [comment]
I have difficulty revoking a particular eCert. 
I was reading yvonneyong's comment on May 2019.
To revoke the eCert, it should be the "target hash" of the file?
Could you assist me on this?
