### ISSUE TITLE
[Feature] Add search functionality  

### ISSUE THREAD

**Issue by sumitnitsurat** [OpenCerts/opencerts-documentation#56]
Filter the document links with the searched keyword.

**Comment by rjchow** [comment]
https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/

**Comment by rjchow** [comment]
https://help.github.com/en/articles/customizing-css-and-html-in-your-jekyll-theme

**Comment by rjchow** [comment]
Hi there,

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />


<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '7231563d1db842994698da0a519e93c8',
indexName: 'opencerts',
inputSelector: '### REPLACE ME ####',
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/styling.html)
- You can also check your configuration in our GitHub repo (https://github.com/algolia/docsearch-configs/blob/master/configs/opencerts.json).
- me@rjchow.com can get access to the full Algolia analytics for your DocSearch index by creating an account, following this link: https://www.algolia.com/users/invitation/accept?invitation_token=yWdysqhysCC85HzkzYaX

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by samuellye98** [comment]
#61
