### ISSUE TITLE
Deployment for the custom templates

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#6]
Hi,

I have tested creating the custom templates by updating the code in the opencerts-website package and it works fine in my localhost. Please advise on the steps to deploy the custom templates code to production.

Please note that we are unable to use either default or custom template as we have specific layout for our project.

Please advise.

Thanks.

**Comment by erwinsg** [comment]
Hi Rui Jie,

I have created a fork of the opencerts-website and when i tried to do npm install, it gives me some errors. Are you able to advise on this? Please refer to attached file.

Thanks.
[Logs_issue_20181012.zip](https://github.com/OpenCerts/opencerts-documentation/files/2472273/Logs_issue_20181012.zip)

**Comment by rjchow** [comment]
Can you use yarn instead of npm for now? Inadvertently used a comment syntax that is accepted by yarn but not npm even though npm says it is acceptable - sorry about that

**Comment by erwinsg** [comment]
Hi Rui Jie,

It is okay, but there is error as well using yarn.

[Logs_issue_20181012_2.zip](https://github.com/OpenCerts/opencerts-documentation/files/2472411/Logs_issue_20181012_2.zip)

**Comment by rjchow** [comment]
Looks like an internet connectivity error?

**Comment by erwinsg** [comment]
Sorry for multiple queries.
For this section: "wait for approval", can we know how long it takes to get it approved?

**Comment by rjchow** [comment]
No worries Erwin

Within 2 work days if there's no issue otherwise we'll just iterate on it until it works
It's not a formal approval process just need Raymond or I to look over it and make sure there's nothing wrong with it

**Comment by erwinsg** [comment]
k thanks.
