### ISSUE TITLE
Unregistered Institution Warning is Wrong

### ISSUE THREAD

**Issue by wmclaxton** [OpenCerts/opencerts-documentation#67]
The information presented when valid certificates from unregistered institutions are being verified is WRONG (https://docs.opencerts.io/identity_registry.html).

1.  The message "has not registered" suggests that the issuer has not completed some part of the expected process, which is not correct.
2. The message "registered with OpenCerts" indicates that the registry is controlled by OpenCerts, which is not correct.  It is maintained by SSG.
3.  The message does not display information regarding whether the certificate is valid, but instead guides the user away from the page.  Only a very confident user would 'proceed anyway' after being warned on your site that the issuer has failed to register.

**Comment by rjchow** [comment]
thanks for the feedback bill, we have some exciting updates in store for you - stay tuned :)

**Comment by yehjxraymond** [comment]
Closing this issue in view of v2.0 release
