### ISSUE TITLE
Version releases

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#68]
We noticed that there is a new version 2.0. We have already developed custom templates on v1.5. Will v1.5 still be supported in the long term? What are the changes we will need to do on our custom templates from v1.5 to v2.0?
How often will there be version releases and is there a roadmap?

**Comment by yehjxraymond** [comment]
Hi Yvonne, we will support previous version as well but there will be instructions to migrate to 2.0 soon. We will no longer be accepting pull request after this year as there will be a new method to create your own renderer without creating a PR to us. Please keep a lookout for the announcement next week. 

Also, on the issue of backward support, we will be adding a flag for the cli to select earlier versions of the schema.

**Comment by yehjxraymond** [comment]
Hi this is now supported in the latest CLI, with the `--schema` flag. Will close this issue now.
