### ISSUE TITLE
OpenCers V2.0

### ISSUE THREAD

**Issue by opencert-sutd** [OpenCerts/opencerts-documentation#73]
For now, new templates should we follow V2.0 and upload templates to Document Renderer or should submit Pull Request to OpenCerts Website?

In Netlify, when we register Custom Domain, should we follow .opencerts.io? or we can add our institution domain name?

**Comment by yehjxraymond** [comment]
Please use your institute's domain name, this is so that only you guys have control over it.

**Comment by yehjxraymond** [comment]
Also, for V2, there is no need for pull request anymore.

**Comment by opencert-sutd** [comment]
After following all steps in Opencert V2.0, I could not access site deployed. its blank.
![issue screen](https://user-images.githubusercontent.com/52150238/62025619-409e2080-b20b-11e9-889a-bdc63f07e44b.JPG)

**Comment by yehjxraymond** [comment]
The page will be blank, you can read the docs to run it on local or over netlify

https://docs.opencerts.io/document_renderer.html#testing-using-the-indexhtml-file

**Comment by yehjxraymond** [comment]
Have added into the appending a slightly more detailed walkthrough: https://docs.opencerts.io/appendix_viewing_template_development.html

Will proceed to close this issue
