### ISSUE TITLE
Hosting own decentralised render for OpenCerts v1.5 after 2019

### ISSUE THREAD

**Issue by khunshwephyo** [OpenCerts/opencerts-documentation#74]
Based on <https://docs.opencerts.io/announcements/schema2_update.html>

![image](https://user-images.githubusercontent.com/25623914/62356728-4fa30c80-b544-11e9-9d05-152b25b08190.png)

Does it mean that after 31 December 2019, institutions **must** host their own decentralized-renderer(s) for v1.4, v1.5 as well as v2.0 opencerts?  

I am assuming that https://opencerts.io is currently deciding which renderer to 'redirect' to.  For example, 

```
if( version < 2 ) {
  url = legacy.opencerts.io;
} else {
  url = getUrlFromOpenCertFile();
}
redirectToDecentralizedRenderer(url);
```
Is there any sample codes for a decentralized renderer to detect v1.4, v1.5, v2.0 and display custom certificate templates?

**Comment by yehjxraymond** [comment]
For existing certificate templates they will be hosted at the legacy repository where we will continue to run it past 31 Dec. You may even make edits to existing templates using pull requests. 

However should you want to introduce new templates after that date, you must host your own renderer as we no longer provide PR reviews for new templates.

To summaries, 1.4 and 1.5 will be hosted by us. V2 will be hosted by you. Decentralised renderer will only render v2 and above certificates.

**Comment by khunshwephyo** [comment]
Thank you.  I understand now.
