### ISSUE TITLE
Document Renderer & Identity Registry

### ISSUE THREAD

**Issue by SUSS-CITS** [OpenCerts/opencerts-documentation#77]
1. For document renderer, do we have to host the renderer at Netlify or we can host it at our own server?
2. For identity registry, do we register at registry.json, DNS-TXT or both?

**Comment by yehjxraymond** [comment]
You may host it anywhere you like, Netlify is only one of the many possibilities.

For identity registry we will prefer you do both, reason being if there are other software providers reading in OpenCerts file but do not subscribe to the registry file, they can still identify the issuers.
