### ISSUE TITLE
OpenCerts 2.0 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/opencerts-documentation#78]
Do we need to reissue certificates issued under OpenCerts v1 in order to use OpenCerts v2.0 ?

**Comment by yehjxraymond** [comment]
We don’t expect you to do so as they will remain valid. If you have not sent them to students then it may make sense for you to reissue. Suggestion is to create new ones with the v2 method and leave the existing ones as is.

**Comment by RP-OIS-SK** [comment]
Does it means that legacy.opencerts.io will still available for cert issued under OpenCerts V1 ? For the future batches of cert, it will be verified under decentralised renderer.  For OpenCerts V1, it is still The Centralised renderer.

**Comment by yehjxraymond** [comment]
Yes correct. All certs prior to v2 will be routed to use legacy.opencerts.io automatically.
