### ISSUE TITLE
registry.json

### ISSUE THREAD

**Issue by opencert-sutd** [OpenCerts/opencerts-documentation#79]
Should we still update our institution in Registry.json if we proceeding with V2.0?

**Comment by yehjxraymond** [comment]
Yes please, that will upgrade the status to be accredited by SSG.

**Comment by opencert-sutd** [comment]
Should I create pull request after editing registry.json? as templates are added in new document renderer.

**Comment by yehjxraymond** [comment]
Yes, in that PR please also attach a demo certificate. Thanks!

**Comment by opencert-sutd** [comment]
updating registry.json is only needed for accredition by SSG? registry.json is not requeired in V2.0 to verify issuer?

**Comment by rjchow** [comment]
SSG accreditation is one of the two ways of issuer verification, other being DNS
refer to https://docs.opencerts.io/dns_verification.html for more details

**Comment by opencert-sutd** [comment]
In DNS-TXT record and Location in Issuer filed is 'openattestation.com' is hardcoded? should we use exact same value?

**Comment by opencert-sutd** [comment]
In DNS-TXT record and Location in Issuer filed is 'openattestation.com' is hardcoded? should we use exact same value?  as below

Also is certificatestore renamed as documentstore V2.0?

"issuers": [
    {
        "network": "ETHEREUM",
        "documentStore": "0xXXXXXXXXXXXXX",
        "identityProof": {
            "type": "DNS-TXT",
            "location": "openattestation.com"
        }
    }
]

**Comment by rjchow** [comment]
please read https://docs.opencerts.io/dns_verification.html and understand it carefully as misconfiguration will result in errors for your users

<openattestation.com> should be the domain you are creating the TXT record at

yes please use documentStore

**Comment by opencert-sutd** [comment]
When I change label from certificateStore to documentStore and batch file again, there is error saying invalid document. 

I am using latest cli tool.
![error](https://user-images.githubusercontent.com/52150238/63248084-2b139800-c299-11e9-8be6-e07807e02271.JPG)

**Comment by opencert-sutd** [comment]
We are not owner of <openattestation.com> domain. Can we still add DNS-TXT at <openattestation.com>?

**Comment by rjchow** [comment]
you're right I made a mistake in my reply earlier - the key is still certificateStore 

DNS-TXT record should be under **your institution's domain**
I also noticed that your template renderer url in the example cert above points to your main site? it should point to the endpoint that you're hosting your renderer at
