### ISSUE TITLE
OpenCert 2.0 viewer issue

### ISSUE THREAD

**Issue by opencert-sutd** [OpenCerts/opencerts-documentation#80]
We have deployed document renderer and try to view, but when we select opencert file, its loading forever. Is there any backend log which we can check, so to understand what is the issue?

Our template url is https://opencert.sutd.edu.sg/ which is pointing to document renderer.

![image](https://user-images.githubusercontent.com/52150238/63414621-d013a980-c42e-11e9-9fe9-2ba912e024e0.png)

![image](https://user-images.githubusercontent.com/52150238/63414668-e883c400-c42e-11e9-8191-6bf0486132b8.png)

![image](https://user-images.githubusercontent.com/52150238/63414759-136e1800-c42f-11e9-8a57-38a84acdb5a7.png)

**Comment by rjchow** [comment]
everything runs clientside so there's no backend log, can you share the cert file so that I can try it?

**Comment by opencert-sutd** [comment]
I have attached zip folder which contain sample opencert file.

[signed_certs.zip](https://github.com/OpenCerts/opencerts-documentation/files/3524261/signed_certs.zip)

**Comment by rjchow** [comment]
have deleted your attachment because it looked like a real students' cert
(this is a publicly viewable issue tracker)

![image](https://user-images.githubusercontent.com/27843274/63415843-ecb0e100-c430-11e9-8e9c-919c7599c739.png)

The error originates from your renderer side, probably an issue with your template code?

**Comment by opencert-sutd** [comment]
I just verified and Template seems fine. Can we proceed to submit Pull Request for Template as in V1.5?

**Comment by rjchow** [comment]
you don't need to submit a pull request if you're hosting your own renderer

i double checked and confirmed it's an issue with your template code, it's not passing the certificate to the template but beyond that you will have to do your own troubleshooting

**Comment by rjchow** [comment]
possible issue is that you changed the document parameter for the template to certificate?

**Comment by opencert-sutd** [comment]
Thanks for update. But if replace certificateStore to documentStore, cli tool triggers error.

![image](https://user-images.githubusercontent.com/52150238/63425675-b335a100-c443-11e9-8390-4fd6f9b19ca8.png)

**Comment by opencert-sutd** [comment]
Latest Cli tool i have downloaded on 06 Aug. should i clone again and download latest?

**Comment by rjchow** [comment]
leave the cert file alone it's the template code that's the issue. in your
templating function it's taking an object with certificate as the key but
in the documentViewerContainer it's passing an object with document as the
key

**Comment by opencert-sutd** [comment]
We face same issue even after modification in template key to document. Is it possible to have conference call to discuss on this issue?

**Comment by rjchow** [comment]
conference calls aren't useful for troubleshooting code, push your code to
a github repo and we can go over it there

**Comment by opencert-sutd** [comment]
Our templates are in OpenCerts/demo-opencerts-renderer. This forked from OpenCerts/demo-opencerts-renderer

**Comment by opencert-sutd** [comment]
Our templates are in opencert-sutd/demo-opencerts-renderer. This forked from OpenCerts/demo-opencerts-renderer

**Comment by rjchow** [comment]
if you're using the same cert file as the one you shared yesterday its missing a SignatoryType field

![image](https://user-images.githubusercontent.com/27843274/63567314-9f08b580-c5a3-11e9-8065-3fa9b9d2cc49.png)

if you're using a different cert please share it so that i can try it

**Comment by opencert-sutd** [comment]
Thanks. Issue is resoved. I am able access opencerts files. 
Its old test file and SignatoryType field is missing in opencert file. 
After adding this field in test file, issue resolved.
So, its not issue with template but missing field in test file.

As this field is missing, when i drag and drop opencert file, its keep on loading and i guess its searching for field in opencert file.

Thanks for support

**Comment by rjchow** [comment]
no prob
