### ISSUE TITLE
Steps/way to install DocumentRenderer in Offline mode

### ISSUE THREAD

**Issue by mohammedkalimullah** [OpenCerts/opencerts-documentation#82]
Hi,
we would like to install the document Render site in internal server which do not have internet connectivity and later we would like to host this in public via reverse proxy.Please advise how to proceed with this.

Also regarding the DNS part, i could not able to understand, could you please elaborate more on this and what is the configuration required from institution side

**Comment by rjchow** [comment]
we are not able to dispense advice on your internal architecture.

As for the DNS, you will need to be able to create DNS-TXT records for your institute's domain as per https://docs.opencerts.io/dns_verification.html

**Comment by mohammedkalimullah** [comment]
it is not about internal architecture. Please advise how we install document renderer site in server which we do not have internet connectivity.

**Comment by yehjxraymond** [comment]
Could you explain why do you have the site on a network with no internet connectivity? We've guide to use services like netlify to do it for free if cost is an issue. If security is an issue, then all the more you shouldnt put a publicly accessible resource (aka decentralised renderer) in a private network.

If you really have a very good reason for that, you can build the application image in a development machine connected to the internet (for dependencies) and then transfer the built image into a production environment.

**Comment by mohammedkalimullah** [comment]
it is due to security, we would like to host internally for all Dev and QA testing.

**Comment by yehjxraymond** [comment]
You should not be putting anything that is not going to publicly accessible in the code anyway. If you need to keep the visuals away from the privy eye, run it in a network that is not accessible from the outside but has internet access from the inside. What it seemed to me now is you are doing it the other way around where you allow traffic from the outside but not from the inside?!

If you must do it the hard way the summary of it is to build it in an environment with internet and then deliver it in an environment without. We will not be providing support on how to build the image for such environment.

**Comment by mohammedkalimullah** [comment]
Hi,
we know how to expose the site publicly via reverse proxy with appropriate security components.

Our IT policy does not allow internal servers to have internet access.
what we required is that, do you have options to install the site in offline mode. if you do not have options or if you do not want to provide details, you can close the ticket.

Thanks

**Comment by yehjxraymond** [comment]
Just build it and then move it to your server without access. You can google how to do that. People typically build it into a docker image and then just serve the image. 

Closing the ticket.
