### ISSUE TITLE
Invalid document error upon batching schema 2.0 json

### ISSUE THREAD

**Issue by SUSS-CITS** [OpenCerts/opencerts-documentation#83]
Hi,

Encountered error upon batching certificate through cli-tool. 
**Error Screenshot:**
![image](https://user-images.githubusercontent.com/49050584/64498284-6d535680-d2e6-11e9-9561-b728c817da2e.png)

**Attempts tried:**
1. Tried to put --schema 2.0 when using cli-tool to define the schema version. 
![image](https://user-images.githubusercontent.com/49050584/64498432-07b39a00-d2e7-11e9-99c3-dd9de592ef80.png)

2. No errors found when JSON input validates against with the schema using https://www.jsonschemavalidator.net/ .

Did I miss out any steps?

**Comment by yehjxraymond** [comment]
Can you attach the file you are trying to batch here? Can rename the extension to .txt to attch

**Comment by SUSS-CITS** [comment]
[SampleTesting.txt](https://github.com/OpenCerts/opencerts-documentation/files/3588511/SampleTesting.txt)

**Comment by yehjxraymond** [comment]
![image](https://user-images.githubusercontent.com/7406870/64504818-152b4d00-d304-11e9-91af-a1bca156c775.png)
[SampleTesting.txt](https://github.com/OpenCerts/opencerts-documentation/files/3588736/SampleTesting.txt)

This is weird, it signs fine on mine you can see the output and attached file above. 

Could you check that you've placed the json file in a folder that only contains pre-batched opencerts file? Also, to be extra sure, can you try re-installing the cli?

**Comment by SUSS-CITS** [comment]
It works after re-installing the cli-tool.

Thanks! :)
