### ISSUE TITLE
Render Signed Certificate

### ISSUE THREAD

**Issue by SUSS-CITS** [OpenCerts/opencerts-documentation#84]
Hi,

Just wondering if we're able to render signed certificate before issuing certificate batch? 

Tried:
1. **Able** to render **unsigned** certificate **before** issuing certificate batch by following document renderer guide
2. **Unable** to render **signed** certificate **before** issuing certificate batch by following renderer guide
3. **Able** to render **signed** certificate **after** issuing certificate batch

Did i miss out something?

**Comment by yehjxraymond** [comment]
Hi, you can use render from the **raw certificate data** (before running the CLI). You can use the `index.html` file in the test folder to render it that way. We do not have methods to render it from the batched form unless it has been issued.

**Comment by yehjxraymond** [comment]
https://github.com/OpenCerts/legacy-templates/blob/master/test/index.html

**Comment by SUSS-CITS** [comment]
Alright, noted. Thanks
