### ISSUE TITLE
DNS-TXT

### ISSUE THREAD

**Issue by SUSS-CITS** [OpenCerts/opencerts-documentation#88]
Hi,

Followed the guide (https://github.com/Open-Attestation/adr/blob/master/decentralized_identity_proof_DNS-TXT.md) to add the txt record in our domain for Ethereum-Ropsten document store. Also edited the issuers to match with schema 2.0. 
`net=ethereum netId=3 addr=<certificate store>
`
![image](https://user-images.githubusercontent.com/49050584/66617647-911cfb80-ec08-11e9-9c37-231cf515f494.png)

However, our certificate still showing "Accredited by SSG" instead of "Issued by Singapore University of Social Sciences". 

Did we miss out any steps?

**Comment by rjchow** [comment]
it’s correct, SSG takes precedence over DNS

**Comment by SUSS-CITS** [comment]
so there's nothing we need to do at our end and just wait for SSG? or inform SSG about this?

**Comment by Nebulis** [comment]
Indeed there is nothing to do on your end, you can inform SSG but they are aware of the situation and we are working with them on this

**Comment by SUSS-CITS** [comment]
When will it be ready?

**Comment by Nebulis** [comment]
You can follow https://github.com/OpenCerts/opencerts-website/pull/428

You can also try https://deploy-preview-428--opencerts-production.netlify.com/

**Comment by SUSS-CITS** [comment]
Thanks for the link, tried and tested.

Any difference between these two:
1. 
![image](https://user-images.githubusercontent.com/49050584/66725702-4220d180-ee67-11e9-9b4a-eb6a3fc2891b.png)

2. 
![image](https://user-images.githubusercontent.com/49050584/66725704-48af4900-ee67-11e9-9ac0-b5d685d5d08b.png)

As per my understanding from the documentation is, screenshot 1 will render an output of "Accredited by SSG"; screenshot 2 will render an output of "Certificate Issued by Singapore University of Social Sciences" 

However, both certificates gave me the same output of "Certificate Issued by Singapore University of Social Sciences" 
![image](https://user-images.githubusercontent.com/49050584/66725799-b5c2de80-ee67-11e9-81ca-7991415a03cc.png)

Just some confusion that I have and need some clarification.

**Comment by rjchow** [comment]
As mentioned earlier, SSG accreditation  takes precedence over DNS
identity, so if you have both it will show SSG. The reason we prefer
institutes to implement both is so that the information is in the cert if
we should ever need it since the cert is immutable once issued.

**Comment by SUSS-CITS** [comment]
Understand, thanks. Shall follow the screenshot 2 of the issuer format.

**Comment by Nebulis** [comment]
FYI the MR has been merged, feel free to open an issue in opencerts-website if needed

**Comment by SUSS-CITS** [comment]
Thanks for informing.
