### ISSUE TITLE
Viewing certs in OpenCert in UAT

### ISSUE THREAD

**Issue by NIECOpencerts** [OpenCerts/opencerts-documentation#95]
Hi,

We are trying to view the cert in OpenCert in UAT with the test data passed over but still unable to view them in the UAT OpenCert environment. How should NIEC move forward so that we can quickly close off the UAT and port over to Production?

Thank you.

Regards
Jerry Siak
Executive
Academic & Student Management
 
Tel: (+65) 6904 2650
Fax: (+65) 6254 1704
 
National Institute of Early Childhood Development
1 Nanyang Walk NIE 5-B2-06
Singapore 637616
www.niec.edu.sg

CONFIDENTIALITY: If this email has been sent to you by mistake, please notify the sender and delete it immediately.

**Comment by Nebulis** [comment]
Hi please share a certificate you have trouble with
