### ISSUE TITLE
Template tested in Localhost with desired Font-famliy and Style works fine however in dev.opencerts.io display differnt font.

### ISSUE THREAD

**Issue by SP-PACE-OpenCert** [OpenCerts/opencerts-documentation#96]
Hi,

I have created a template with below font-family and style, when I test in localhost it works fine however when I validate in dev.opencerts.io, the font displays different style. Attached the signed JSON and Localhost result and OpenCert validated Cert.

Code as follows in .JS file.

style={{fontFamily:'Gill Sans,Gill Sans MT,Calibri,sans-serif' 

Thanks,
Solai Kani
+65-91157167
 
[Issue_SP_PACE.zip](https://github.com/OpenCerts/opencerts-documentation/files/3987324/Issue_SP_PACE.zip)

**Comment by Nebulis** [comment]
Hi,

I'm not sure why it works locally for you but here is what I notice:
- There is not ttf or woff file for `Gill Sans` font
- JS code is correct (the generated html is trying to load the font as you expected)

You should register the TTF using `@font-face` => https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

**Comment by SP-PACE-OpenCert** [comment]
Message Classification: Official (Closed)

Hi,

Can you please assist me to register https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face?

I cannot find any registration option.

Regards,
Solai Kani

**Comment by Nebulis** [comment]
I'm not sure what you mean by *registration* but to use a font you have to proceed as follow:

- host the font somewhere (optional can reuse a hosted font if available in any cdn or in google fonts for instance)
- load the font
```css
    font-family: "<Font Family Name>";
    src: url("https://url-to-font");
```
- use the font
```css
    body { font-family: "<Font Family Name>", serif }
```
