### ISSUE TITLE
Special characters are replaced after signing

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#99]
We've been having issues where special characters are replaced after signing the cert.
The original generated JSON file had the character, eg. é and ’ and we could render them fine with our template. However, after signing the certs with the CLI Tool, those characters were replaced by � and so this new symbol would be rendered instead. New cases keep getting discovered, and the certs need to be revoked, fixed and re-issued. Please advise how this can be resolved holistically.

**Comment by Nebulis** [comment]
Which version of the cli do you use ?, could you provide a sample (before wrapping)

**Comment by yvonneyong** [comment]
[screenshots.zip](https://github.com/OpenCerts/opencerts-documentation/files/4256315/screenshots.zip)

**Comment by yvonneyong** [comment]
We are on V2.0

**Comment by Nebulis** [comment]
Did you check the content of the wrapped certificate ? the images provided see a problem in the UI, so if the content of the wrapped certificate is correct, then that means that the issue is on the renderer (the renderer doesn't handle UTF-8 correctly)

**Comment by yvonneyong** [comment]
![2020-02-26 23_03_50 (JSON after signing)](https://user-images.githubusercontent.com/50482118/75357530-7d8adc80-58ec-11ea-8921-9def289b3466.png)

The JSON content does change after signing, as can be seen in this screenshot.
The renderer URL we are using is the same before and after signing, so it's strange if it can handle UTF-8 before and not after signing?

**Comment by Nebulis** [comment]
Yeah in that case it's not from the renderer. I downloaded the file and notice that it's not using utf-8 encoding, but iso-8859-1. Could you use utf-8 instead

**Comment by yvonneyong** [comment]
This method worked for us.
Thank you!
